import { Fact, RelationType } from "./types";

export interface SeedCaseItem {
  id: string;
  relation: RelationType;
  entity: string;
  attribute: string;
  valueA: string;
  valueB?: string;
  docA: string;
  docB?: string;
  pageA: number;
  pageB?: number;
  quoteA: string;
  quoteB?: string;
  explanation: string;
  rules_applied: string[];
  confidence: number;
}

export const SEED_FACTS: Record<string, Fact> = {
  "seed-corroborates-a": {
    id: "seed-corroborates-a",
    document_id: "seed-doc-1",
    document_filename: "01-delhivery-prospectus-2022-excerpt.pdf",
    page: 28,
    bbox: [72, 140, 520, 185],
    entity: "Delhivery",
    attribute: "express_parcel_volume",
    entity_canon: "Delhivery",
    attribute_canon: "Express Parcel Volume",
    raw_value: "578 million",
    norm_value: 578000000,
    norm_unit: "units",
    currency: null,
    period: "FY2022",
    scope: "Consolidated Express",
    quote: "Express parcel shipment volume reached 578 million shipments in Fiscal 2022.",
    confidence: 0.98,
    model: "llama-3.3-70b-versatile",
    prompt_ver: "extract_v2",
    relations: [
      {
        relation_id: "seed-rel-corroborates",
        relation: "corroborates",
        explanation:
          "Both prospectus and annual report assert identical 578 million express parcel shipments for Fiscal 2022.",
        rules_applied: ["R1_exact_match", "R2_temporal_alignment"],
        confidence: 0.99,
        counterpart_id: "seed-corroborates-b",
        quote: "In FY22, the Company handled 578 million express parcel shipments.",
        document_filename: "02-delhivery-annual-report-fy24-excerpt.pdf",
        page: 31,
      },
    ],
  },
  "seed-corroborates-b": {
    id: "seed-corroborates-b",
    document_id: "seed-doc-2",
    document_filename: "02-delhivery-annual-report-fy24-excerpt.pdf",
    page: 31,
    bbox: [65, 210, 510, 245],
    entity: "Delhivery",
    attribute: "express_parcel_volume",
    entity_canon: "Delhivery",
    attribute_canon: "Express Parcel Volume",
    raw_value: "578 million",
    norm_value: 578000000,
    norm_unit: "units",
    currency: null,
    period: "FY2022",
    scope: "Express Parcel",
    quote: "In FY22, the Company handled 578 million express parcel shipments.",
    confidence: 0.97,
    model: "llama-3.3-70b-versatile",
    prompt_ver: "extract_v2",
  },
  "seed-contradicts-a": {
    id: "seed-contradicts-a",
    document_id: "seed-doc-2",
    document_filename: "02-delhivery-annual-report-fy24-excerpt.pdf",
    page: 42,
    bbox: [80, 310, 530, 360],
    entity: "Delhivery",
    attribute: "adjusted_ebitda",
    entity_canon: "Delhivery",
    attribute_canon: "Adjusted EBITDA",
    raw_value: "₹461 Cr",
    norm_value: 4610000000,
    norm_unit: "INR",
    currency: "INR",
    period: "FY2024",
    scope: "Consolidated",
    quote: "Adjusted EBITDA for FY24 stood at ₹461 Cr reflecting a margin of 5.7% of operational revenue.",
    confidence: 0.94,
    model: "llama-3.3-70b-versatile",
    prompt_ver: "extract_v2",
    relations: [
      {
        relation_id: "seed-rel-contradicts",
        relation: "contradicts",
        explanation:
          "Discrepancy of ₹38 Cr (8.2%) between Annual Report (₹461 Cr) and Q4 Presentation (₹423 Cr) for FY24 Adjusted EBITDA.",
        rules_applied: ["R2_numerical_mismatch", "R5_temporal_collision"],
        confidence: 0.95,
        counterpart_id: "seed-contradicts-b",
        quote: "FY24 Adjusted EBITDA reported at ₹423 Cr (margin 5.2%) before post-audit reconciliation adjustments.",
        document_filename: "03-delhivery-q4-fy24-earnings-presentation.pdf",
        page: 14,
      },
    ],
  },
  "seed-contradicts-b": {
    id: "seed-contradicts-b",
    document_id: "seed-doc-3",
    document_filename: "03-delhivery-q4-fy24-earnings-presentation.pdf",
    page: 14,
    bbox: [95, 180, 540, 225],
    entity: "Delhivery",
    attribute: "adjusted_ebitda",
    entity_canon: "Delhivery",
    attribute_canon: "Adjusted EBITDA",
    raw_value: "₹423 Cr",
    norm_value: 4230000000,
    norm_unit: "INR",
    currency: "INR",
    period: "FY2024",
    scope: "Consolidated Pre-audit",
    quote: "FY24 Adjusted EBITDA reported at ₹423 Cr (margin 5.2%) before post-audit reconciliation adjustments.",
    confidence: 0.93,
    model: "llama-3.3-70b-versatile",
    prompt_ver: "extract_v2",
  },
  "seed-variance-a": {
    id: "seed-variance-a",
    document_id: "seed-doc-2",
    document_filename: "02-delhivery-annual-report-fy24-excerpt.pdf",
    page: 112,
    bbox: [75, 410, 525, 460],
    entity: "Delhivery",
    attribute: "revenue_operations",
    entity_canon: "Delhivery",
    attribute_canon: "Revenue from Operations",
    raw_value: "₹8,142 Cr",
    norm_value: 81420000000,
    norm_unit: "INR",
    currency: "INR",
    period: "FY2024",
    scope: "Consolidated Total",
    quote: "Consolidated Revenue from contracts with customers reached ₹8,142 Cr for the fiscal year ended March 31, 2024.",
    confidence: 0.96,
    model: "llama-3.3-70b-versatile",
    prompt_ver: "extract_v2",
    relations: [
      {
        relation_id: "seed-rel-variance",
        relation: "contextual_variance",
        explanation:
          "Variance stems from reporting scope: Earnings presentation reports core transport operations (₹7,860 Cr), excluding supply chain and cross-border freight included in consolidated filing (₹8,142 Cr).",
        rules_applied: ["R3_scope_contextual_variance"],
        confidence: 0.92,
        counterpart_id: "seed-variance-b",
        quote: "Core Express parcel & Part Truckload logistics operational revenue stood at ₹7,860 Cr in FY24.",
        document_filename: "03-delhivery-q4-fy24-earnings-presentation.pdf",
        page: 8,
      },
    ],
  },
  "seed-variance-b": {
    id: "seed-variance-b",
    document_id: "seed-doc-3",
    document_filename: "03-delhivery-q4-fy24-earnings-presentation.pdf",
    page: 8,
    bbox: [85, 230, 520, 275],
    entity: "Delhivery",
    attribute: "revenue_operations",
    entity_canon: "Delhivery",
    attribute_canon: "Revenue from Operations",
    raw_value: "₹7,860 Cr",
    norm_value: 78600000000,
    norm_unit: "INR",
    currency: "INR",
    period: "FY2024",
    scope: "Core Transport Only",
    quote: "Core Express parcel & Part Truckload logistics operational revenue stood at ₹7,860 Cr in FY24.",
    confidence: 0.91,
    model: "llama-3.3-70b-versatile",
    prompt_ver: "extract_v2",
  },
  "seed-failure-a": {
    id: "seed-failure-a",
    document_id: "seed-doc-1",
    document_filename: "01-delhivery-prospectus-2022-excerpt.pdf",
    page: 98,
    bbox: [70, 500, 510, 545],
    entity: "Delhivery",
    attribute: "active_pincodes",
    entity_canon: "Delhivery",
    attribute_canon: "Active Pincodes Coverage",
    raw_value: "over 18,500",
    norm_value: 18500,
    norm_unit: "pincodes",
    currency: null,
    period: "Unspecified Date",
    scope: "Fuzzy Boundary",
    quote: "Delhivery provides reach to over 18,500 pincodes across India through its integrated hub network.",
    confidence: 0.42,
    model: "llama-3.3-70b-versatile",
    prompt_ver: "extract_v2",
  },
};

export const SEED_REVIEW_ITEMS: import("./types").ReviewItem[] = [
  {
    id: "review-anomaly-1",
    fact_id: "seed-contradicts-a",
    relation_id: "seed-rel-contradicts",
    reason: "contradiction",
    status: "pending",
    decision: "Discrepancy of ₹38 Cr (8.2%) between Annual Report (₹461 Cr) and Q4 Presentation (₹423 Cr) for FY24 Adjusted EBITDA.",
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    entity_canon: "Delhivery",
    attribute_canon: "Adjusted EBITDA",
    raw_value: "₹461 Cr",
    norm_value: 4610000000,
    fact_confidence: 0.94,
    quote: "Adjusted EBITDA for FY24 stood at ₹461 Cr reflecting a margin of 5.7% of operational revenue.",
    filename: "02-delhivery-annual-report-fy24-excerpt.pdf",
    document_id: "seed-doc-2",
    page: 42,
    bbox: [80, 310, 530, 360],
    counterpart: {
      id: "seed-contradicts-b",
      entity_canon: "Delhivery",
      attribute_canon: "Adjusted EBITDA",
      raw_value: "₹423 Cr",
      norm_value: 4230000000,
      quote: "FY24 Adjusted EBITDA reported at ₹423 Cr (margin 5.2%) before post-audit reconciliation adjustments.",
      filename: "03-delhivery-q4-fy24-earnings-presentation.pdf",
      document_id: "seed-doc-3",
      page: 14,
      bbox: [95, 180, 540, 225],
    },
  },
  {
    id: "review-anomaly-2",
    fact_id: "seed-variance-a",
    relation_id: "seed-rel-benford",
    reason: "anomaly:benford",
    status: "pending",
    decision: "First-digit Benford distribution anomaly detected (χ²=28.4, p<0.01). Significant variance on leading digits 7 and 9.",
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    entity_canon: "Delhivery",
    attribute_canon: "Numeric Facts Distribution",
    raw_value: "χ² = 28.4 (Expected < 15.5)",
    norm_value: 28.4,
    fact_confidence: 0.89,
    quote: "Cross-footing and first-digit statistical profile on 48 reported numeric ledger entries.",
    filename: "02-delhivery-annual-report-fy24-excerpt.pdf",
    document_id: "seed-doc-2",
    page: 112,
    bbox: [75, 410, 525, 460],
  },
  {
    id: "review-anomaly-3",
    fact_id: "seed-variance-a",
    relation_id: "seed-rel-variance",
    reason: "contextual_variance",
    status: "pending",
    decision: "Reporting scope divergence: Core transport revenue (₹7,860 Cr) vs Consolidated multi-service revenue (₹8,142 Cr).",
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    entity_canon: "Delhivery",
    attribute_canon: "Revenue from Operations",
    raw_value: "₹8,142 Cr",
    norm_value: 81420000000,
    fact_confidence: 0.96,
    quote: "Consolidated Revenue from contracts with customers reached ₹8,142 Cr for the fiscal year ended March 31, 2024.",
    filename: "02-delhivery-annual-report-fy24-excerpt.pdf",
    document_id: "seed-doc-2",
    page: 112,
    bbox: [75, 410, 525, 460],
    counterpart: {
      id: "seed-variance-b",
      entity_canon: "Delhivery",
      attribute_canon: "Revenue from Operations",
      raw_value: "₹7,860 Cr",
      norm_value: 78600000000,
      quote: "Core Express parcel & Part Truckload logistics operational revenue stood at ₹7,860 Cr in FY24.",
      filename: "03-delhivery-q4-fy24-earnings-presentation.pdf",
      document_id: "seed-doc-3",
      page: 8,
      bbox: [85, 230, 520, 275],
    },
  },
  {
    id: "review-anomaly-4",
    fact_id: "seed-failure-a",
    reason: "low_confidence",
    status: "pending",
    decision: "Extraction confidence 0.42 is below 0.50 threshold. Temporal period unspecified in prospectus excerpt.",
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    entity_canon: "Delhivery",
    attribute_canon: "Active Pincodes Coverage",
    raw_value: "over 18,500",
    norm_value: 18500,
    fact_confidence: 0.42,
    quote: "Delhivery provides reach to over 18,500 pincodes across India through its integrated hub network.",
    filename: "01-delhivery-prospectus-2022-excerpt.pdf",
    document_id: "seed-doc-1",
    page: 98,
    bbox: [70, 500, 510, 545],
  },
  {
    id: "review-anomaly-5",
    fact_id: "seed-corroborates-a",
    reason: "anomaly:zscore",
    status: "pending",
    decision: "Z-score outlier (>3.2σ from group mean): Parcel volume surge exceeds peer standard distribution.",
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    entity_canon: "Delhivery",
    attribute_canon: "Express Parcel Volume",
    raw_value: "578 million",
    norm_value: 578000000,
    fact_confidence: 0.98,
    quote: "Express parcel shipment volume reached 578 million shipments in Fiscal 2022.",
    filename: "01-delhivery-prospectus-2022-excerpt.pdf",
    document_id: "seed-doc-1",
    page: 28,
    bbox: [72, 140, 520, 185],
    counterpart: {
      id: "seed-corroborates-b",
      entity_canon: "Delhivery",
      attribute_canon: "Express Parcel Volume",
      raw_value: "578 million",
      norm_value: 578000000,
      quote: "In FY22, the Company handled 578 million express parcel shipments.",
      filename: "02-delhivery-annual-report-fy24-excerpt.pdf",
      document_id: "seed-doc-2",
      page: 31,
      bbox: [65, 210, 510, 245],
    },
  },
];
